### ISSUE TITLE
Prepare for the big split

### ISSUE THREAD

**Issue by matthiasnoback** [LongRunning/LongRunning#10]
In order to split the LongRunning repository into multiple ones and allow people to install small packages instead of this big one, the following steps should be taken:
- We need a separate composer.json file for:
  - The Core
  - The Bundle
  - Each of the plugins
- All files for a package should be contained in one directory per package (i.e. src and tests), e.g. src/Plugin/DoctrineDBALPlugin/ also contains a directory Tests containing the tests
- The LongRunning repo will run all the tests for all the packages, so the packages themselves don't need phpunit.xml.dist nor .travis.yml files.
- We need to set up repositories for each of the packages
- We need to put a .gitsplit.yml in the root of the project, like this one: https://github.com/elcodi/bamboo/blob/master/.gitsplit.yml
- Finally, we can hook up the project at http://gitsplit.com, a tool by @mmoreram

By the way, @mmoreram, do we miss anything here?

**Comment by mmoreram** [comment]
@matthiasnoback Nopes!

That should be enough :+1: 

Ping me when you're ready!

**Comment by matthiasnoback** [comment]
@mmoreram Thanks!

**Comment by cmodijk** [comment]
I'm closing this one because we have my #16 pull request for this.
