### ISSUE TITLE
Form processing in background tasks

### ISSUE THREAD

**Issue by westende** [LongRunning/LongRunning#11]
Hi guys,

I am using your bundle for cleaning up during long running RabbitMQ Consumer runs which make use of simplebus.

However I had memory issues cleaning up when importing data using previously built Sonata admins and forms. There were two root causes.
1. Sonata - This was easily resolved.
2. Symfony core - Symfony core keeps track of all forms in the FormDataCollector. I implemented an extending class with a clean method in order to clean up.

``` php
use Symfony\Component\Form\Extension\DataCollector\FormDataCollector as BaseFormDataCollector;

class FormDataCollector extends BaseFormDataCollector
{
    public function clear()
    {
        // Set private property dataByForm to null
        $reflectionClass = new \ReflectionClass('Symfony\Component\Form\Extension\DataCollector\FormDataCollector');

        $reflectionProperty = $reflectionClass->getProperty('dataByForm');
        $reflectionProperty->setAccessible(true);
        $reflectionProperty->setValue($this, null);

        // Unset forms
        unset($this->data['forms']);
    }
} 
```

I am not sure this can be applied to your bundle or will be of interest, but it's worth a shot.

Also see: https://groups.google.com/forum/#!topic/sonata-devs/RyGltXOP7f0

Cheers!

**Comment by cmodijk** [comment]
I think it's better to create a pull request for the symfony core and that we could implement a clear cleaner in LongRunning. I personally don't like to use reflection to solve these kinds of problems. But i think the symfony team word be interested at this.

**Comment by matthiasnoback** [comment]
Well, the best solution would be to disable collecting/profiling entirely. You should be able to disable it by not loading related bundles/modifying framework configuration for a particular environment. For CLI applications I always like to define a special environment, like "cli". Run commands with --env=cli and create a config_cli.yml file which is optimized for low memory usage and less debugging, etc.

**Comment by matthiasnoback** [comment]
Sorry, accidentally closed it.

**Comment by westende** [comment]
@cmodijk: Will do. No fan either of this solution, but it's the only way I knew to solve this issue.
@matthiasnoback: I wasn't aware that the FormDataCollector is part of the profiler. Defining a specific environment for these kinds of things makes sense. Thanks!

**Comment by matthiasnoback** [comment]
@piepkrak Perfect, I think because of the fact that this is related to profiling, it wouldn't make sense to submit a fix as a PR, since profiling is supposed to work only for the current request anyway.

Okay, will close this issue now :)

**Comment by westende** [comment]
@matthiasnoback: You are right. Creating a dedicated environment circumvented the profiler-related issue with the FormDataCollector altogether. A pull request is indeed not necessary. Thank you guys for your help and time.

**Comment by matthiasnoback** [comment]
@piepkrak You're welcome
