### ISSUE TITLE
Clear container

### ISSUE THREAD

**Issue by cmodijk** [LongRunning/LongRunning#12]
The symfony dependency injection container got a new function to clear al services https://github.com/symfony/symfony/pull/15185. I'm not sure what the impact would be if we would create a cleaner for that and use it in a running RabbitMQ consumer but i'm just leaving this here as a idea we could implement.

**Comment by matthiasnoback** [comment]
Interesting!

**Comment by cmodijk** [comment]
I'm closing this because i don't have the time to test this and it is open for almost a year know,
