### ISSUE TITLE
Reset monolog

### ISSUE THREAD

**Issue by cmodijk** [LongRunning/LongRunning#2]
We use the fingers_crossed logger and when we nou get an error in one command al logs and commands after that one is writing to disk. The `FingersCrossedHandler` has an reset and clear method maybe we could use this to reset it? 

https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/FingersCrossedHandler.php

**Comment by matthiasnoback** [comment]
That's a great idea!

**Comment by cmodijk** [comment]
I'm looking into this one 
- I think we should `close` the `BufferHandler` after every run to empty it's messages and let the next handler handles the messages. 
- For the `FingersCrossedHandler` we should `reset` it because if the passthru level is not reached the messages should be destroyed.

Does any one know how to get all the handlers? Because it's possible to have nested handlers. For instance I could have the BufferHandler after the FingersCrossedHandler and you can't get the child handlers.

**Comment by matthiasnoback** [comment]
Cool!

To find all the handlers of a specific type you should create a compiler pass and collect all the services with the class you're interested in, like:

``` php
$bufferHandlerServiceReferences = [];
foreach ($container->getDefinitions() as $serviceId => $definition) {
  if ($definition->getClass() === '...\BufferHandler') {
    $bufferHandlerServiceReferences[] = new Reference($serviceId);
  }
}
```
