### ISSUE TITLE
Events not resetting after each handler

### ISSUE THREAD

**Issue by TNAJanssen** [LongRunning/LongRunning#20]
When you have an event with 2 handlers, one fails the other one doesn't the entity manager etc are not reset!

**Comment by cmodijk** [comment]
@TNAJanssen After which handlers the `LongRunning` project only listens to a few events like i listed below by default if you enabled them. If we want these to be active on other places we need check on which places we want to implement these cleaners and create a implementation for them. Could you explain what your use case is where you wold expext the cleaners to be run? 
* bernard.acknowledge
* bernard.reject
* simple_bus.rabbit_mq_bundle_bridge.message_consumed
* simple_bus.rabbit_mq_bundle_bridge.message_consumption_failed

**Comment by TNAJanssen** [comment]
@cmodijk i debugged i bit further, sometimes the reset of the entity manager fails.

There is nothing handling that at the moment!
