### ISSUE TITLE
Database driver connections are not actually closed in a long running process or worker

### ISSUE THREAD

**Issue by sjoerdmaessen** [LongRunning/LongRunning#21]
In the plugin "LongRunning\Plugin\DoctrineDBALPlugin\CloseConnections" a call is made to the close() method of each connection managed by the Doctrine Registry. The Doctrine close method will simply set the protected $_conn property to null, which should close the actual driver connection if there are no other references to this connection, PDO in my case. 
If I watch the number of MySQL connections on the CLI I see the number of connections increasing all the time when my long running process is running, even though I see it's closing all my connections after each command that is served by RabbitMQ. My conclusion is there is still a reference to an entity manager in one of my command handlers that is used by my long running process (worker). 

Whats the preferred way of dealing with this situation? Do you simply always call the entity manager inside your command handlers from the registry and do you never assign it to a variable?

edit: I was using `show status like '%onn%';` to view the number of connections but this status variable doesn't show the actual number of open connections but merely the number of successful connection attempts. https://dev.mysql.com/doc/refman/5.7/en/server-status-variables.html#statvar_Connections however I'm still having too many open connections

edit2: I refactored my code where I always pull the connection from the registry in my workers instead of using it from class variables which seems to have solved my problem with the amount of connections that kept open.

**Comment by matthiasnoback** [comment]
Excellent issue :) Thanks for posting, maybe someone else stumbles upon this issue too.

Closing this, since there isn't anything that needs fixing, right?

**Comment by cmodijk** [comment]
This is a very interesting case I just read up how PHP close the connection for PDO but it only does that when al references to it are removed. That is interesting.. So if doctrine or someone has a reference to it the connection it will not close. But this also means that if there is a circular reference the PHP Garbage Collection needs to handle this but this only kicks in once every 10.000 objects i think? 

> The connection remains active for the lifetime of that PDO object. To close the connection, you need to destroy the object by ensuring that all remaining references to it are deleted--you do this by assigning NULL to the variable that holds the object. If you don't do this explicitly, PHP will automatically close the connection when your script ends.

Sources
* https://stackoverflow.com/questions/18277233/pdo-closing-connection
* http://php.net/manual/en/pdo.connections.php
