### ISSUE TITLE
doctrine ping test

### ISSUE THREAD

**Issue by ivan1986** [LongRunning/LongRunning#25]
in [DoctrineDBALPlugin/CloseConnections.php](https://github.com/LongRunning/LongRunning/blob/master/src/Plugin/DoctrineDBALPlugin/CloseConnections.php)
why need close connection every time, isn't better use?

            if (false === $connection->ping()) {
                $connection->close();
                $connection->connect();
            }

**Comment by ruudk** [comment]
Going forward we're no longer supporting Doctrine DBAL anymore (only ORM).
