### ISSUE TITLE
Dependency problems with swiftmailer in symfony 4.3

### ISSUE THREAD

**Issue by jkobus** [LongRunning/LongRunning#40]
Hello. I'm upgrading an app from sf 3.4 to 4.3 and it seems that the latest version of the long-running bundle rejects to work due to some container-related changes in symfony:

> The service "MyWrapper" has a dependency on a non-existent service "swiftmailer.mailer.default.spool".

The reference "swiftmailer.mailer.default.spool" is a private alias.

Where "MyWrapper" looks like:

```
use LongRunning\Core\Cleaner as LongRunningBundleCleaner;

class MyWrapper {
   private $longRunningCleaner;

    public function __construct(LongRunningBundleCleaner $longRunningCleaner)
    {
        $this->longRunningCleaner = $longRunningCleaner;
    }

    public function cleanUp(): void
    {
        $this->longRunningCleaner->cleanUp();
    }
}
```

I'm still investigating this but so far it seems that the problem is gone after adding line shown below in SwiftMailerPass.php:

```
$container->setAlias('swiftmailer.mailer.default.spool', new Alias('swiftmailer.mailer.default.spool.memory', true));
```

Maybe someone with greater knowledge will be able to point me in the right direction.

Thanks.

**Comment by ruudk** [comment]
Going forward we're no longer supporting SwiftMailer anymore.
